[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "APP"
version = "1.6"
requires-python = ">=3.12,<3.13"

dependencies = [
    "fastapi==0.118.0",
    "uvicorn>=0.30.0",
    "numpy==2.3.2",
    "pandas==2.3.3",
    "tqdm==4.67.1",    
    "SQLAlchemy==2.0.43",
    "psycopg[binary]==3.3.1",
    "python-dotenv==1.1.0",    
    "pytest==8.3.3",
    "folium==0.17.0",
    "pillow==11.0.0",

]

[tool.hatch.build.targets.wheel]
packages = ["APP"] 

